sudo: required
services:
  - docker

before_install:
  - docker build -t ali/docker-react -f Dockerfile.dev .

script:
  - docker run ali/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-1-217573409016'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id:
    secure: $AWS_KEY_ACCESS_NEW
  secret_access_key:
    secure: $AWS_SECRET_KEY
